[binaries]
# Don't add arguments here. We have to pass  -stdlib=libc++ only
# because without it, meson can't even use clang++
cpp=['clang++', '-stdlib=libc++']
c=['clang']
cpp_ld='lld'
c_ld='lld'

# Important - meson can not actually reconfigure itself. After changing
# anything here, you MUST delete your build library and make meson setup
# again
[built-in options]
default_library='static'
cpp_args=['-stdlib=libc++', '-fexperimental-library', '-pedantic', '-g2' ]
c_args=[]
#cpp_link_args=[]
#c_link_args=[]

[properties]
buildtype='debug'

[spdlog:project options]
tests='disabled'
# external_fmt='enabled'

[fmt:built-in options]
default_library='static'

[abseil-cpp:built-in options]
cpp_args=['-Wno-gcc-compat']

[protobuf:project options]
install=false

[lua-5.4:project options]
interpreter=false

[lua-5.4:built-in options]
c_args=['-xc++']

[lua:project options]
interpreter=false
lua_cpp=true

[lua:built-in options]
c_args=['-xc++']
