--- This file was automatically generated by generate_lua_godot_api.py
--- @meta

--- @param angle_rad float
--- @return float
function sin(angle_rad) end

--- @param angle_rad float
--- @return float
function cos(angle_rad) end

--- @param angle_rad float
--- @return float
function tan(angle_rad) end

--- @param x float
--- @return float
function sinh(x) end

--- @param x float
--- @return float
function cosh(x) end

--- @param x float
--- @return float
function tanh(x) end

--- @param x float
--- @return float
function asin(x) end

--- @param x float
--- @return float
function acos(x) end

--- @param x float
--- @return float
function atan(x) end

--- @param y float
--- @param x float
--- @return float
function atan2(y, x) end

--- @param x float
--- @return float
function asinh(x) end

--- @param x float
--- @return float
function acosh(x) end

--- @param x float
--- @return float
function atanh(x) end

--- @param x float
--- @return float
function sqrt(x) end

--- @param x float
--- @param y float
--- @return float
function fmod(x, y) end

--- @param x float
--- @param y float
--- @return float
function fposmod(x, y) end

--- @param x int
--- @param y int
--- @return int
function posmod(x, y) end

--- @param x any
--- @return any
function floor(x) end

--- @param x float
--- @return float
function floorf(x) end

--- @param x float
--- @return int
function floori(x) end

--- @param x any
--- @return any
function ceil(x) end

--- @param x float
--- @return float
function ceilf(x) end

--- @param x float
--- @return int
function ceili(x) end

--- @param x any
--- @return any
function round(x) end

--- @param x float
--- @return float
function roundf(x) end

--- @param x float
--- @return int
function roundi(x) end

--- @param x any
--- @return any
function abs(x) end

--- @param x float
--- @return float
function absf(x) end

--- @param x int
--- @return int
function absi(x) end

--- @param x any
--- @return any
function sign(x) end

--- @param x float
--- @return float
function signf(x) end

--- @param x int
--- @return int
function signi(x) end

--- @param x any
--- @param step any
--- @return any
function snapped(x, step) end

--- @param x float
--- @param step float
--- @return float
function snappedf(x, step) end

--- @param x float
--- @param step int
--- @return int
function snappedi(x, step) end

--- @param base float
--- @param exp float
--- @return float
function pow(base, exp) end

--- @param x float
--- @return float
function log(x) end

--- @param x float
--- @return float
function exp(x) end

--- @param x float
--- @return bool
function is_nan(x) end

--- @param x float
--- @return bool
function is_inf(x) end

--- @param a float
--- @param b float
--- @return bool
function is_equal_approx(a, b) end

--- @param x float
--- @return bool
function is_zero_approx(x) end

--- @param x float
--- @return bool
function is_finite(x) end

--- @param x float
--- @param curve float
--- @return float
function ease(x, curve) end

--- @param x float
--- @return int
function step_decimals(x) end

--- @param from any
--- @param to any
--- @param weight any
--- @return any
function lerp(from, to, weight) end

--- @param from float
--- @param to float
--- @param weight float
--- @return float
function lerpf(from, to, weight) end

--- @param from float
--- @param to float
--- @param pre float
--- @param post float
--- @param weight float
--- @return float
function cubic_interpolate(from, to, pre, post, weight) end

--- @param from float
--- @param to float
--- @param pre float
--- @param post float
--- @param weight float
--- @return float
function cubic_interpolate_angle(from, to, pre, post, weight) end

--- @param from float
--- @param to float
--- @param pre float
--- @param post float
--- @param weight float
--- @param to_t float
--- @param pre_t float
--- @param post_t float
--- @return float
function cubic_interpolate_in_time(from, to, pre, post, weight, to_t, pre_t, post_t) end

--- @param from float
--- @param to float
--- @param pre float
--- @param post float
--- @param weight float
--- @param to_t float
--- @param pre_t float
--- @param post_t float
--- @return float
function cubic_interpolate_angle_in_time(from, to, pre, post, weight, to_t, pre_t, post_t) end

--- @param start float
--- @param control_1 float
--- @param control_2 float
--- @param _end float
--- @param t float
--- @return float
function bezier_interpolate(start, control_1, control_2, _end, t) end

--- @param start float
--- @param control_1 float
--- @param control_2 float
--- @param _end float
--- @param t float
--- @return float
function bezier_derivative(start, control_1, control_2, _end, t) end

--- @param from float
--- @param to float
--- @return float
function angle_difference(from, to) end

--- @param from float
--- @param to float
--- @param weight float
--- @return float
function lerp_angle(from, to, weight) end

--- @param from float
--- @param to float
--- @param weight float
--- @return float
function inverse_lerp(from, to, weight) end

--- @param value float
--- @param istart float
--- @param istop float
--- @param ostart float
--- @param ostop float
--- @return float
function remap(value, istart, istop, ostart, ostop) end

--- @param from float
--- @param to float
--- @param x float
--- @return float
function smoothstep(from, to, x) end

--- @param from float
--- @param to float
--- @param delta float
--- @return float
function move_toward(from, to, delta) end

--- @param from float
--- @param to float
--- @param delta float
--- @return float
function rotate_toward(from, to, delta) end

--- @param deg float
--- @return float
function deg_to_rad(deg) end

--- @param rad float
--- @return float
function rad_to_deg(rad) end

--- @param lin float
--- @return float
function linear_to_db(lin) end

--- @param db float
--- @return float
function db_to_linear(db) end

--- @param value any
--- @param min any
--- @param max any
--- @return any
function wrap(value, min, max) end

--- @param value int
--- @param min int
--- @param max int
--- @return int
function wrapi(value, min, max) end

--- @param value float
--- @param min float
--- @param max float
--- @return float
function wrapf(value, min, max) end

--- @param arg1 any
--- @param arg2 any
--- @return any
function max(arg1, arg2, ...) end

--- @param a int
--- @param b int
--- @return int
function maxi(a, b) end

--- @param a float
--- @param b float
--- @return float
function maxf(a, b) end

--- @param arg1 any
--- @param arg2 any
--- @return any
function min(arg1, arg2, ...) end

--- @param a int
--- @param b int
--- @return int
function mini(a, b) end

--- @param a float
--- @param b float
--- @return float
function minf(a, b) end

--- @param value any
--- @param min any
--- @param max any
--- @return any
function clamp(value, min, max) end

--- @param value int
--- @param min int
--- @param max int
--- @return int
function clampi(value, min, max) end

--- @param value float
--- @param min float
--- @param max float
--- @return float
function clampf(value, min, max) end

--- @param value int
--- @return int
function nearest_po2(value) end

--- @param value float
--- @param length float
--- @return float
function pingpong(value, length) end

function randomize() end

--- @return int
function randi() end

--- @return float
function randf() end

--- @param from int
--- @param to int
--- @return int
function randi_range(from, to) end

--- @param from float
--- @param to float
--- @return float
function randf_range(from, to) end

--- @param mean float
--- @param deviation float
--- @return float
function randfn(mean, deviation) end

--- @param base int
function seed(base) end

--- @param seed int
--- @return PackedInt64Array
function rand_from_seed(seed) end

--- @param obj any
--- @return any
function weakref(obj) end

--- @param variant any
--- @param type int
--- @return any
function type_convert(variant, type) end

--- @param arg1 any
--- @return String
function str(arg1, ...) end

--- @param error int
--- @return String
function error_string(error) end

--- @param type int
--- @return String
function type_string(type) end

--- @param arg1 any
function print(arg1, ...) end

--- @param arg1 any
function print_rich(arg1, ...) end

--- @param arg1 any
function printerr(arg1, ...) end

--- @param arg1 any
function printt(arg1, ...) end

--- @param arg1 any
function prints(arg1, ...) end

--- @param arg1 any
function printraw(arg1, ...) end

--- @param arg1 any
function print_verbose(arg1, ...) end

--- @param arg1 any
function push_error(arg1, ...) end

--- @param arg1 any
function push_warning(arg1, ...) end

--- @param variable any
--- @return String
function var_to_str(variable) end

--- @param string String
--- @return any
function str_to_var(string) end

--- @param variable any
--- @return PackedByteArray
function var_to_bytes(variable) end

--- @param bytes PackedByteArray
--- @return any
function bytes_to_var(bytes) end

--- @param variable any
--- @return PackedByteArray
function var_to_bytes_with_objects(variable) end

--- @param bytes PackedByteArray
--- @return any
function bytes_to_var_with_objects(bytes) end

--- @param variable any
--- @return int
function hash(variable) end

--- @param instance_id int
--- @return Object
function instance_from_id(instance_id) end

--- @param id int
--- @return bool
function is_instance_id_valid(id) end

--- @param instance any
--- @return bool
function is_instance_valid(instance) end

--- @return int
function rid_allocate_id() end

--- @param base int
--- @return RID
function rid_from_int64(base) end

--- @param a any
--- @param b any
--- @return bool
function is_same(a, b) end
