extends Object

enum CellNeighbor {
	RIGHT_SIDE = 0,
	RIGHT_CORNER = 1,
	BOTTOM_RIGHT_SIDE = 2,
	BOTTOM_RIGHT_CORNER = 3,
	BOTTOM_SIDE = 4,
	BOTTOM_CORNER = 5,
	BOTTOM_LEFT_SIDE = 6,
	BOTTOM_LEFT_CORNER = 7,
	LEFT_SIDE = 8,
	LEFT_CORNER = 9,
	TOP_LEFT_SIDE = 10,
	TOP_LEFT_CORNER = 11,
	TOP_SIDE = 12,
	TOP_CORNER = 13,
	TOP_RIGHT_SIDE = 14,
	TOP_RIGHT_CORNER = 15,
}
