syntax = "proto3";

package hs.proto.scope;

import "types/scope_type.proto";

message NumericModifier {
  string key = 1;
  double add = 2;
  double mult = 3;
}

message NumericVariable {
  string id = 1;
  repeated NumericModifier modifiers = 2;
  uint64 modification_time = 3;
}

message StringModifier {
  string key = 1;
  string value = 2;
  double level = 3;
}

message StringVariable {
  string id = 1;
  repeated StringModifier modifiers = 2;
  uint64 modification_time = 3;
}

message Scope {
  string id = 1;
  types.ScopeType scope_type = 2;
  repeated NumericVariable numeric_variables = 3;
  repeated StringVariable string_variables = 4;
  repeated string tag_scope_ids = 5;
}
