extends RefCounted

class_name EK

const ERR_INTERNAL_SELECTED_CELL_IS_INVALID = &"ERR_INTERNAL_SELECTED_CELL_IS_INVALID"

const ERR_INTERNAL_FAILED_TO_CREATE_SCOPE = &"ERR_INTERNAL_FAILED_TO_CREATE_SCOPE"
